services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper
  backend:
    build: ./backend
    ports:
      - "3002:3001"  # Host:Container (Backend in container runs on 3001, exposed as 3002 on host)
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
  frontend:
    build: ./frontend
    ports:
      - "3003:3000"  # Host:Container, adjust host port if you want
    environment:
      - NODE_ENV=production
    depends_on:
      - backend     # Only if you have a backend service
