version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
