apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
  - name: DS_PROMETHEUS
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: DS_PROMETHEUS
